steps:

  - label: ":arrow_down: Load AlgebraicJulia pipeline"
    command: |
      curl -s https://raw.githubusercontent.com/AlgebraicJulia/.github/buildkite/buildkite/pipeline.yml | buildkite-agent pipeline upload

  - wait
