steps:

  - label: "Testing order of operations"
    command:
      - "module load julia"
      - "julia --project=docs --color=yes -e 'using Pkg; Pkg.update(); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.precompile()'"

  - wait

  - label: ":arrow_down: Load AlgebraicJulia pipeline"
    command: |
      curl -s https://raw.githubusercontent.com/AlgebraicJulia/.github/main/buildkite/pipeline.yml | buildkite-agent pipeline upload

  - wait
