steps:

  - label: ":arrow_down: Load AlgebraicJulia pipeline"
    command: |
      if [ -f ".buildkite/example.yml" ]; then
        buildkite-agent pipeline upload .buildkite/example.yml
      else
        curl -s https://raw.githubusercontent.com/AlgebraicJulia/.github/main/buildkite/pipeline.yml | buildkite-agent pipeline upload
      fi
        

  - wait
