steps:

  - label: "Running benchmarks"
    env:
      JULIA_PROJECT = "benchmarks/"
    command: |
      ./benchmarks/scripts/main.sh

  - wait

  - label: ":arrow_down: Load AlgebraicJulia pipeline"
    command: |
      curl -s https://raw.githubusercontent.com/AlgebraicJulia/.github/main/buildkite/pipeline.yml | buildkite-agent pipeline upload

  - wait
